  on:
    push:
      branches:
        - master











  jobs: 
    build:
      runs-on: ubuntu-latest

      steps:
        - name: 'print file data before'
          run: ls


        - uses: actions/checkout@v3

        - name: 'print file data after'
          run: ls
